/**
 * Kök düzen (Root Layout): App Router'da TÜM sayfaları saran şablon.
 * .NET MVC'de _Layout.cshtml'e veya Blazor'da MainLayout.razor'a benzer.
 * Bu dosya varsayılan olarak Server Component'tir ("use client" yok).
 */

// next/font/google: Google Fonts'u build zamanında optimize eder (self-host, layout shift azaltır).
import { Geist, Geist_Mono } from "next/font/google";

// Global stiller: Tailwind ve :root değişkenleri globals.css içinde.
import "./globals.css";

// Font örnekleri: CSS değişkeni olarak HTML'e enjekte edilir (--font-geist-sans vb.).
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * metadata: Next.js'e özel; <head> içindeki title, description, Open Graph vb. için kullanılır.
 * Server Component'lerde export edilebilir; .NET'te ViewData["Title"] veya <head> yönetimine benzer.
 */
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * children: İç sayfa (ör. page.js) buraya yerleştirilir — layout iç içe geçebilir (klasör bazlı routing).
 */
export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      // className ile font değişkenlerini köke veriyoruz; alt bileşenler aynı aileden tipografi kullanabilir.
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* flex flex-col: İleride footer/header ile dikey düzen için uygun esnek kutu modeli */}
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
